/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-16 10:43:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class appinsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("     <meta charset=\"UTF-8\">\r\n");
      out.write("    \r\n");
      out.write("     <title>Insert title here</title>\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"home1.css\">\r\n");
      out.write("\r\n");
      out.write(" <style>\r\n");
      out.write(" \r\n");
      out.write(" body, h2, form, label, input, select, textarea, button {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .form-wrapper {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #f5f7fa;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: flex-start; \r\n");
      out.write("            min-height: 100vh; \r\n");
      out.write("            padding: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            background-color: #2d004d;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: calc(100% - 20px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin: 10px 0 5px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"],\r\n");
      out.write("        input[type=\"date\"],\r\n");
      out.write("        textarea,\r\n");
      out.write("        select {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            background: #f9f9f9;\r\n");
      out.write("            transition: background 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        textarea {\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            resize: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"date\"] {\r\n");
      out.write("            color: #400040;\r\n");
      out.write("            background: #eef2f7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input:focus,\r\n");
      out.write("        textarea:focus {\r\n");
      out.write("            background: #e8f0fe;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border: 1px solid rgb(74, 0, 74);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write(".submit {\r\n");
      out.write("            width: 70%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            background: #000;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 17px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .disabled-button {\r\n");
      out.write("            background-color: #808080;\r\n");
      out.write("            cursor: not-allowed;\r\n");
      out.write("            border: none;\r\n");
      out.write("            width: 70%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 17px;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .para {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #2d004d;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error-message {\r\n");
      out.write("            color: red;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            margin-top: -5px;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("        <h1 class=\"home-h1\">CARE  CONNECT</h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("               <b> <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">Submit a Ticket</a></li>\r\n");
      out.write("                <li><a href=\"#\">FAQs</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact Us</a></li></b>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"home-button-container\">\r\n");
      out.write("        <a href=\"#\"><button class=\"b1\"><b>Work With Us</b></button></a>\r\n");
      out.write("        <a href=\"#\"><button class=\"b1\"><b>Contact Expert</b></button></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"form-wrapper\">\r\n");
      out.write("  <div class=\"form-container\">\r\n");
      out.write("      <h2>Appointment Form</h2>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"insertapp\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                \r\n");
      out.write("            	<label>Full Name :</label>\r\n");
      out.write("            	<input type=\"text\"  name=\"aname\"  placeholder=\"Enter Full Name\" required>\r\n");
      out.write("\r\n");
      out.write("                <label>Email :</label>\r\n");
      out.write("                <input type=\"text\"  name=\"aemail\" id=\"email\" required/>\r\n");
      out.write("                <span id=\"email-error\" class=\"error-message\"></span> <br>\r\n");
      out.write("                \r\n");
      out.write("                <label>Expert Name :</label>\r\n");
      out.write("                <select name=\"ename\" required>\r\n");
      out.write("                    <option value=\"\" disabled selected>Select an Expert</option>\r\n");
      out.write("                    <option value=\"Professor David Wang\">Professor David Wang</option>\r\n");
      out.write("                    <option value=\"Mr. Johnathan\">Mr. Johnathan</option>\r\n");
      out.write("                    <option value=\"Mrs. Emily\">Mrs. Emily</option>\r\n");
      out.write("                    <option value=\"Mr. Perera\">Mr. Perera</option>\r\n");
      out.write("                    <option value=\"Mr. Gomez\">Mr. Gomez</option>\r\n");
      out.write("                </select>\r\n");
      out.write("\r\n");
      out.write("                <label>Preferred Date :</label>\r\n");
      out.write("                <input type=\"date\"  name=\"date\"   required/>\r\n");
      out.write("\r\n");
      out.write("                <label>Concern</label>\r\n");
      out.write("                <textarea id=\"concern\" name=\"concern\" placeholder=\"Enter your concern here\" rows=\"4\"></textarea>\r\n");
      out.write("                <span id=\"concern-error\" class=\"error-message\"></span> <br>\r\n");
      out.write("                \r\n");
      out.write("                <input type=\"checkbox\" onclick=\"enablebutton()\" id=\"checkbox\" ><b><span class=\"para\" > I agree to the privacy policy and consultation guidelines</span></b> <br><br>\r\n");
      out.write("                \r\n");
      out.write("                <center><b><button type=\"submit\" id=\"submitBTN\"  class=\"disabled-button\" class=\"submit\" disabled>Submit</button></b></center>\r\n");
      out.write("\r\n");
      out.write("         </form>\r\n");
      out.write("   </div></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    \r\n");
      out.write("     function validateForm() \r\n");
      out.write("    {\r\n");
      out.write("    	  //validate the email\r\n");
      out.write("    	\r\n");
      out.write("    	  var email = document.getElementById(\"email\").value.trim();\r\n");
      out.write("  	      var errorEmailMessage =  document.getElementById(\"email-error\");\r\n");
      out.write("  	   \r\n");
      out.write("  	      var emailpattern = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("  	   \r\n");
      out.write("  	   \r\n");
      out.write("  	       if (!emailpattern.test(email)) {\r\n");
      out.write("  		       errorEmailMessage.textContent = \"*Please enter a valid email address.\";\r\n");
      out.write("               return false;\r\n");
      out.write("           } else {\r\n");
      out.write("      	        errorEmailMessage.textContent = \"\";\r\n");
      out.write("           }\r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("    	//validation for the context text length\r\n");
      out.write("    	   var concern = document.getElementById(\"concern\").value.trim();\r\n");
      out.write("           var errorMessage = document.getElementById(\"concern-error\");\r\n");
      out.write("        \r\n");
      out.write("            if (concern.length < 10 || concern.length > 50)\r\n");
      out.write("            {\r\n");
      out.write("                errorMessage.textContent = \"*Concern should be between 10 and 50 characters long.\";\r\n");
      out.write("                return false;\r\n");
      out.write("            } else\r\n");
      out.write("            {\r\n");
      out.write("                \r\n");
      out.write("            	errorMessage.textContent = \"\";\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            return true;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //enable the submit button of the form\r\n");
      out.write("     function enablebutton()\r\n");
      out.write("     {\r\n");
      out.write("         	if(document.getElementById(\"checkbox\").checked)\r\n");
      out.write("     	   {\r\n");
      out.write("     		      document.getElementById(\"submitBTN\").disabled=false;\r\n");
      out.write("                  document.getElementById(\"submitBTN\").classList.remove(\"disabled-button\");\r\n");
      out.write("                  document.getElementById(\"submitBTN\").classList.add(\"submit\");\r\n");
      out.write("     	   }\r\n");
      out.write("     	   else\r\n");
      out.write("     	   {\r\n");
      out.write("     		      document.getElementById(\"submitBTN\").disabled=true;\r\n");
      out.write("                  document.getElementById(\"submitBTN\").classList.add(\"disabled-button\");\r\n");
      out.write("                  document.getElementById(\"submitBTN\").classList.remove(\"submit\");\r\n");
      out.write("     	   }\r\n");
      out.write("     	\r\n");
      out.write("     	\r\n");
      out.write("     }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
