/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-15 07:58:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"home1.css\">\r\n");
      out.write(" <style>\r\n");
      out.write(" \r\n");
      out.write("body {\r\n");
      out.write("    background-color: rgb(235,253,221); \r\n");
      out.write("    color: black; \r\n");
      out.write("    font-family: Arial, sans-serif; \r\n");
      out.write("    line-height: 1.6; \r\n");
      out.write("    padding: 20px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("    color: #070707;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("    color:	#f3e7bc; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("    color:	white; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("    color: #0c0c0c; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("section {\r\n");
      out.write("    margin-top: 20px; \r\n");
      out.write("    background-color: #3b2b42; \r\n");
      out.write("    border: 3px solid #2b2330;\r\n");
      out.write("    border-radius: 8px; \r\n");
      out.write("    padding: 15px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".update-box {\r\n");
      out.write("    margin-top: 10px; \r\n");
      out.write("    background-color:#C0C0C0; \r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".support-box {\r\n");
      out.write("    margin-top: 10px; \r\n");
      out.write("    background-color:#C0C0C0; \r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".resources ul {\r\n");
      out.write("    list-style-type: none; \r\n");
      out.write("    padding: 0; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".resources li {\r\n");
      out.write("    margin-top: 5px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".testimonials {\r\n");
      out.write("    margin-top: 20px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote {\r\n");
      out.write("    background-color:#C0C0C0; \r\n");
      out.write("    padding: 10px; \r\n");
      out.write("    border-left: 4px solid #191a2d; \r\n");
      out.write("    margin: 10px 0; \r\n");
      out.write("    color:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background: #333;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("    background: #333;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: 20px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".home-h1 {\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("    background-color: #FAFAD2;\r\n");
      out.write("    height: 34px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin: 0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a {\r\n");
      out.write("    color: black;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".home-button {\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    background-color:rgb(235,253,221);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".b1 {\r\n");
      out.write("    background-color: #555;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <header>\r\n");
      out.write("        <h1 class=\"home-h1\">CARE CONNECT</h1><br>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("            \r\n");
      out.write("               <b> <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"ticketinsert.jsp\">Submit a Ticket</a></li>\r\n");
      out.write("                <li><a href=\"feedback_Insert.jsp\">Feedback</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("                <li><a href=\"useraccount.jsp\">UserAccount</a></li></b> \r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"home-button\">\r\n");
      out.write("      \r\n");
      out.write("       <a href=\"employeeInsert.jsp\"><button class=\"b1\"><b>Work With Us</b> </button></a>\r\n");
      out.write("        <a href=\"appinsert.jsp\"><button class=\"b1\"><b>Contact Expert</b></button></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("        <center><h1>Welcome to the Care Connect Help Desk</h1></center>\r\n");
      out.write("        <center>  <p><b>Your reliable partner in managing support requests and providing solutions.</b></p></center>\r\n");
      out.write("        \r\n");
      out.write("        <section class=\"overview\">\r\n");
      out.write("            <h2>Overview</h2>\r\n");
      out.write("            <h4>At Care Connect, we are committed to providing exceptional support to our users. Whether you have a technical issue or need assistance navigating our platform, our team is here to help you. Below are various resources to help you get started.</h4>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"updates\">\r\n");
      out.write("            <h2>Recent Updates</h2>\r\n");
      out.write("            <div class=\"update-box\">\r\n");
      out.write("                <h3>Update 1: System Maintenance</h3>\r\n");
      out.write("                <p>We will be performing scheduled maintenance on our systems on October 20th from 2 AM to 4 AM. During this time, the service may be temporarily unavailable.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"update-box\">\r\n");
      out.write("                <h3>Update 2: New Features</h3>\r\n");
      out.write("                <p>Check out our new feature that allows you to track the status of your tickets in real-time! Available now in your account dashboard.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"support-options\">\r\n");
      out.write("            <h2>Support Options</h2>\r\n");
      out.write("            <div class=\"support-box\">\r\n");
      out.write("                <h3>Live Chat Support</h3>\r\n");
      out.write("                <p>Our support team is available for live chat from 9 AM to 5 PM, Monday to Friday. Click the chat icon on the bottom right to get started.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"support-box\">\r\n");
      out.write("                <h3>Email Support</h3>\r\n");
      out.write("                <p>If you prefer, you can reach us via email at . We aim to respond within 24 hours.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"support-box\">\r\n");
      out.write("                <h3>Phone Support</h3>\r\n");
      out.write("                <p>For urgent issues, call our support line at (123) 456-7890, available 24/7.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"resources\">\r\n");
      out.write("            <h2>Helpful Resources</h2>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li></li>\r\n");
      out.write("                <li></li>\r\n");
      out.write("                <li></li>\r\n");
      out.write("                <li></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"testimonials\">\r\n");
      out.write("            <h2>What Our Users Say</h2>\r\n");
      out.write("            <blockquote>\r\n");
      out.write("                <p>\"The support team at Care Connect is amazing! They resolved my issue quickly and were very helpful.\" - Evgenia </p>\r\n");
      out.write("            </blockquote>\r\n");
      out.write("            <blockquote>\r\n");
      out.write("                <p>\"I love the new ticket tracking feature. It's so easy to see the status of my requests!\" - Maxwell Richardson</p>\r\n");
      out.write("            </blockquote>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div><br><br>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <h4>© 2024 Care Connect. All rights reserved.</h4>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
